import { Metadata } from "next";
import HeroUIWrapper from "@/providers/HeroUIWrapper";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
import ManropeFontProvider from "@/providers/fonts/Manrope/ManropeFontProvider";

export const metadata: Metadata = {
  title: "NextJS Stater Kit",
  description: "Generated by Rafi NextJS Stater Kit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ManropeFontProvider>
          <NextTopLoader easing="ease" showSpinner={false} />
          <HeroUIWrapper>{children}</HeroUIWrapper>
        </ManropeFontProvider>
      </body>
    </html>
  );
}
